name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build using Maven
        run: |
          mvn -B package --file pom.xml

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Run Tests using Maven
        run: |
          mvn test

  check_commits_convention:
    name: Conventional Commits Message
    runs-on: ubuntu-latest

    steps:
      - uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:feat|fix|chore|test|docs|build|ci|style|refactor|perf|revert|hotfix)(?:\(\w+\))?:\s[a-z]{1,2}.+'
          error: 'The commit message must have the following structure: <type>(?): <description>'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  check_branches_convention:
    name: Conventional Branches Name
    runs-on: ubuntu-latest

    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z]+)/([a-z]+)'
          allowed_prefixes: 'stable,fix,chore,docs,feat,build,ci,refactor,perf,hotfix'
          ignore: main,release,develop,feature,test
          min_length: 4
          max_length: 100
